apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapplication-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanditasahu/devsecops-demo:25
        ports:
        - containerPort: 8080
